name: PlatformIO CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    env: 
      ENABLE_PAGES_PUSH: ${{ ( github.repository_owner == 'PlummersSoftwareLLC' && github.ref == 'refs/heads/main' ) || ( github.repository_owner == 'rbergen' && github.ref == 'refs/heads/staging' ) }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install PlatformIO and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        pio pkg install --no-save
        pio pkg update --no-save

    - name: Copy secrets and clear SSID
      run: | 
        grep -v "^#define cszSSID" include/secrets.example.h > include/secrets.h
        echo '#define cszSSID ""' >> include/secrets.h

    - name: Build all environments
      run: |
        cp platformio.ini platformio.ini.orig
        grep -v ^default_envs platformio.ini.orig > platformio.ini
        pio run

    - name: Build WebInstaller
      if: ${{ env.ENABLE_PAGES_PUSH == 'true' }}
      run: | 
        python tools/bake_installer.py
        touch WebInstaller/.nojekyll

    - name: Push to GitHub Pages
      if: ${{ env.ENABLE_PAGES_PUSH == 'true' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: pages
        FOLDER: WebInstaller